from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Dict, Any

from communication.message_schema import MessageType


class RiskLevel(str, Enum):
    SAFE = "SAFE"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


class VehicleAction(str, Enum):
    CONTINUE = "CONTINUE"
    SLOW_DOWN = "SLOW_DOWN"
    BRAKE = "BRAKE"


@dataclass
class SafetyDecision:
    """
    Final safety decision generated by the
    safety engine.
    """

    risk: RiskLevel
    action: VehicleAction
    reason: str


def evaluate_safety(
    receiver: Dict[str, Any],
    sender: Dict[str, Any],
    message_type: MessageType,
    obstacle_critical_distance: float = 50.0,
    obstacle_warning_distance: float = 100.0,
    ttc_critical_seconds: float = 2.0,
    ttc_warning_seconds: float = 5.0,
) -> SafetyDecision:

    # ==========================================
    # EMERGENCY BRAKE
    # ==========================================

    if message_type == MessageType.EMERGENCY_BRAKE:

        return SafetyDecision(
            risk=RiskLevel.CRITICAL,
            action=VehicleAction.BRAKE,
            reason="Relevant vehicle reported emergency braking",
        )

    # ==========================================
    # OBSTACLE ALERT
    # ==========================================

    if message_type == MessageType.OBSTACLE_ALERT:

        obstacle_distance = float(
            sender.get(
                "obstacle_distance",
                999.0,
            )
        )

        receiver_position = float(
            receiver["position"]
        )

        receiver_speed = float(
            receiver["speed"]
        )

        sender_position = float(
            sender["position"]
        )

        sender_speed = float(
            sender["speed"]
        )

        # ======================================
        # TTC CALCULATION
        # ======================================

        from intelligence.ttc import calculate_ttc

        ttc_result = calculate_ttc(
            receiver_position=receiver_position,
            receiver_speed=receiver_speed,
            sender_position=sender_position,
            sender_speed=sender_speed,
        )

        # ======================================
        # CRITICAL — VERY LOW TTC
        # ======================================

        if (
            ttc_result.ttc is not None
            and
            ttc_result.ttc <= ttc_critical_seconds
        ):

            return SafetyDecision(
                risk=RiskLevel.CRITICAL,
                action=VehicleAction.BRAKE,
                reason=(
                    f"Critical TTC: "
                    f"{ttc_result.ttc:.2f} seconds"
                ),
            )

        # ======================================
        # WARNING — LOW TTC
        # ======================================

        if (
            ttc_result.ttc is not None
            and
            ttc_result.ttc <= ttc_warning_seconds
        ):

            return SafetyDecision(
                risk=RiskLevel.WARNING,
                action=VehicleAction.SLOW_DOWN,
                reason=(
                    f"Warning TTC: "
                    f"{ttc_result.ttc:.2f} seconds"
                ),
            )

        # ======================================
        # CRITICAL — OBSTACLE DISTANCE
        # ======================================

        if obstacle_distance <= obstacle_critical_distance:

            return SafetyDecision(
                risk=RiskLevel.CRITICAL,
                action=VehicleAction.BRAKE,
                reason=(
                    f"Obstacle distance is "
                    f"{obstacle_distance:.1f}"
                ),
            )

        # ======================================
        # WARNING — OBSTACLE DISTANCE
        # ======================================

        if obstacle_distance <= obstacle_warning_distance:

            return SafetyDecision(
                risk=RiskLevel.WARNING,
                action=VehicleAction.SLOW_DOWN,
                reason=(
                    f"Obstacle distance is "
                    f"{obstacle_distance:.1f}"
                ),
            )

        # ======================================
        # SAFE
        # ======================================

        return SafetyDecision(
            risk=RiskLevel.SAFE,
            action=VehicleAction.CONTINUE,
            reason="No immediate collision risk detected",
        )

    # ==========================================
    # DEFAULT
    # ==========================================

    return SafetyDecision(
        risk=RiskLevel.SAFE,
        action=VehicleAction.CONTINUE,
        reason="No immediate safety event",
    )

from intelligence.relevance import (
    evaluate_message_relevance,
)


def evaluate_message_safety(
    message,
    receiver: Dict[str, Any],
    max_relevant_distance: float = 30.0,
    obstacle_critical_distance: float = 50.0,
    obstacle_warning_distance: float = 100.0,
):
    """
    Complete relevance → safety pipeline.

    A message must first be relevant to the
    receiver before a safety decision is made.
    """

    relevance = evaluate_message_relevance(
        message=message,
        receiver=receiver,
        max_relevant_distance=max_relevant_distance,
    )

    # ------------------------------------------
    # NOT RELEVANT
    # ------------------------------------------

    if not relevance.relevant:

        return relevance, None

    # ------------------------------------------
    # RELEVANT → SAFETY ANALYSIS
    # ------------------------------------------

    sender = message.payload.copy()

    sender["vehicle_id"] = message.sender_id

    decision = evaluate_safety(
        receiver=receiver,
        sender=sender,
        message_type=message.message_type,
        obstacle_critical_distance=(
            obstacle_critical_distance
        ),
        obstacle_warning_distance=(
            obstacle_warning_distance
        ),
    )

    return relevance, decision